# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.RuleElement')),
            ],
            options={
                'ordering': ('rule', 'order'),
            },
        ),
        migrations.CreateModel(
            name='DateRule',
            fields=[
                ('baserule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.BaseRule')),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('planner.baserule',),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('baserule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.BaseRule')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('planner.baserule',),
        ),
        migrations.CreateModel(
            name='SimpleRule',
            fields=[
                ('baserule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.BaseRule')),
                ('name', models.CharField(max_length=50)),
                ('wkst', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('freq', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('HOURLY', 'Hourly'), ('MINUTELY', 'Minutely'), ('SECONDLY', 'Secondly')], default='YEARLY', max_length=10)),
                ('byweekday', models.CharField(blank=True, default=None, max_length=25)),
                ('bymonth', models.CharField(blank=True, default=None, max_length=50)),
                ('bysetpos', models.CharField(blank=True, default=None, max_length=50)),
                ('bymonthday', models.CharField(blank=True, default=None, max_length=50)),
                ('byyearday', models.CharField(blank=True, default=None, max_length=200)),
                ('byweekno', models.CharField(blank=True, default=None, max_length=200)),
                ('byhour', models.CharField(default='0', max_length=200)),
                ('byminute', models.CharField(default='0', max_length=200)),
                ('bysecond', models.CharField(default='0', max_length=200)),
                ('byeaster', models.CharField(blank=True, default=None, max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('planner.baserule',),
        ),
        migrations.AddField(
            model_name='ruleelement',
            name='baserule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.BaseRule'),
        ),
        migrations.AddField(
            model_name='baserule',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_planner.baserule_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rulesetelements',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.RuleSet'),
        ),
    ]
